baseURL = "https://paleprude.com/"
languageCode = "en"
defaultContentLanguage = "en"
theme = "lynx"
title = "Pale Prude's Links"
copyright = "© 2024 Pale Prude"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
   name = "Pale Prude"
  headline = "Photographer and Videographer"
   image = "img/paleprude.jpg"  # path relative to static directory

  links = [
      { flickr = "https://www.flickr.com/paleprudephoto/" },
      { instagram = "https://instagram.com/paleprudephoto" },
      { bluesky = {href = "https://bsky.app/profile/paleprudephoto.bsky.social", text = "Bluesky", icon = "bluesky" } },
      { x = {href = "https://x.com/paleprudephoto", text = "Photo X"} },
      { youtube = {href = "https://www.youtube.com/@paleprude", text = "Video Content"} },
      { twitter = {href = "https://twitter.com/paleprude", text = "Video Twitter"} },
      { kit = {href = "https://kit.co/paleprude", text = "List of the gear that I use.", icon = "kit" } },
      { kofi = {href = "https://ko-fi.com/paleprude", text = "Like what I do? I accept tips!😊", icon = "kofi" } },
    # { email = "mailto:hello@your_domain.com" },
    # { link = "https://link-to-some-website.com/" },
    # { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
    # { apple = "https://www.apple.com" },
    # { codepen = "https://codepen.io/username" },
    # { dev = "https://dev.to/username" },
    # { discord = "https://discord.gg/invitecode" },
    # { dribbble = "https://dribbble.com/username" },
    # { facebook = "https://facebook.com/username" },
    # { flickr = "https://www.flickr.com/photos/username/" },
    # { foursquare = "https://foursquare.com/username" },
    # { github = "https://github.com/username" },
    # { gitlab = "https://gitlab.com/username" },
    # { google = "https://www.google.com/" },
    # { instagram = "https://instagram.com/username" },
    # { keybase = "https://keybase.io/username" },
    # { kickstarter = "https://www.kickstarter.com/profile/username" },
    # { lastfm = "https://last.fm/user/username" },
    # { linkedin = "https://linkedin.com/in/username" },
    # { mastodon = "https://mastodon.instance/@username" },
    # { medium = "https://medium.com/username" },
    # { microsoft = "https://www.microsoft.com/" },
    # { patreon = "https://www.patreon.com/username" },
    # { pinterest = "https://pinterest.com/username" },
    # { reddit = "https://reddit.com/user/username" },
    # { slack = "https://workspace.url/team/userid" },
    # { snapchat = "https://snapchat.com/add/username" },
    # { soundcloud = "https://soundcloud.com/username" },
    # { spotify = "https://spotify.com/user/username" },
    # { stack-exchange = "https://stackexchange.com/users/userid/username" },
    # { stack-overflow = "https://stackoverflow.com/users/userid/username" },
    # { steam = "https://steamcommunity.com/profiles/userid" },
    # { telegram = "https://t.me/username" },
    # { threads = "https://threads.com/username" },
    # { tiktok = "https://tiktok.com/@username" },
    # { tumblr = "https://username.tumblr.com" },
    # { twitch = "https://twitch.tv/username" },
    # { twitter = "https://twitter.com/username" },
    # { whatsapp = "https://wa.me/phone-number" },
    # { x = "https://x.com/username" },
    # { youtube = "https://youtube.com/username" },
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"

[params]
favicon = "img/favicon.png"